---
name: Test API Calls
on:
#   workflow_call:
#     inputs:
#       environment:
#         required: true
#         type: string
#   workflow_dispatch:
    push:
        branches:
            [api-tests]

jobs:
  api-test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        test: ["rollups/01-aln"]
    #environment: ${{ inputs.environment }}
    env:
      #ENV: TESTING
      FAC_API_KEY: ${{ secrets.FAC_API_KEY }}
      FAC_API_URL: ${{ secrets.FAC_API_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.12'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Create .env
        run: touch .env

      - name: Run Test
        working-directory: ${{matrix.test}}/
        run: python main.py



